name: cd

on:
  push:
    branches:
      - main

env:
  HF_ORG_NAME: ${{ vars.HF_ORG_NAME }}
  HF_USERNAME: ${{ secrets.HF_USERNAME }}
  HF_TOKEN: ${{ secrets.HF_TOKEN }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true
      - name: Deploy to Huggingface Spaces
        run: git push https://$HF_USERNAME:$HF_TOKEN@huggingface.co/spaces/$HF_ORG_NAME/README main
